Allow Client HTTP Engine Registration
resteasy/resteasy-microprofile pull request #20
Opened 2021-11-01 11:02 UTC by liweinan

2021-11-01 20:04 UTC, jamezp requested changes

2021-11-01 20:04 UTC, jamezp commented on rest-client-base/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
> +                    registerEngine = true;
This should break after this.
```java
for (Object p : getBuilderDelegate().getProviderFactory().getProviderInstances()) {
    if (p instanceof ClientHttpEngine) {
        resteasyClientBuilder.httpEngine((ClientHttpEngine) p);
        registerEngine = true;
        break;
    }
}
```

2021-11-01 23:06 UTC, liweinan commented on rest-client-base/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
> +                    registerEngine = true;
okay!

2021-11-02 15:11 UTC, jamezp commented
Replaced by #23

2021-11-02 15:11 UTC, closed without merging